// Dummy campaigns data
export const campaigns = [
  {
    CampaignName: 'Summer Sale',
    documentId: 'CMP001',
    status: 'live',
    advertisments: [{ adType: 'Banner' }, { adType: 'Video' }],
  },
  {
    CampaignName: 'Winter Promo',
    documentId: 'CMP002',
    status: 'Expired',
    advertisments: [{ adType: 'Banner' }],
  },
  {
    CampaignName: 'Springsss Launch',
    documentId: 'CMP003',
    status: 'Draft',
    advertisments: [{ adType: 'Video' }],
  },
  {
    CampaignName: 'Autumn Deals',
    documentId: 'CMP004',
    status: 'Live',
    advertisments: [{ adType: 'Banner' }, { adType: 'Banner' }],
  },
  {
    CampaignName: 'Black Friday',
    documentId: 'CMP005',
    status: 'Expired',
    advertisments: [{ adType: 'Video' }, { adType: 'Banner' }],
  },
  {
    CampaignName: 'Cyber Monday',
    documentId: 'CMP006',
    status: 'Draft',
    advertisments: [{ adType: 'Banner' }],
  },
  {
    CampaignName: 'Holiday Blast',
    documentId: 'CMP007',
    status: 'Live',
    advertisments: [{ adType: 'Video' }, { adType: 'Banner' }],
  },
  {
    CampaignName: 'New Year Promo',
    documentId: 'CMP008',
    status: 'Expired',
    advertisments: [{ adType: 'Banner' }],
  },
  {
    CampaignName: "Valentine's Special",
    documentId: 'CMP009',
    status: 'Draft',
    advertisments: [{ adType: 'Video' }],
  },
  {
    CampaignName: 'Easter Deals',
    documentId: 'CMP010',
    status: 'Live',
    advertisments: [{ adType: 'Banner' }, { adType: 'Video' }],
  },
  {
    CampaignName: 'Back to School',
    documentId: 'CMP011',
    status: 'Expired',
    advertisments: [{ adType: 'Banner' }],
  },
  {
    CampaignName: 'Super Bowl',
    documentId: 'CMP012',
    status: 'Draft',
    advertisments: [{ adType: 'Video' }],
  },
  {
    CampaignName: 'Spring Savings',
    documentId: 'CMP013',
    status: 'Live',
    advertisments: [{ adType: 'Banner' }, { adType: 'Banner' }],
  },
  {
    CampaignName: 'Summer Kickoff',
    documentId: 'CMP014',
    status: 'Expired',
    advertisments: [{ adType: 'Video' }],
  },
  {
    CampaignName: 'Labor Day',
    documentId: 'CMP015',
    status: 'Draft',
    advertisments: [{ adType: 'Banner' }],
  },
  {
    CampaignName: 'Halloween Bash',
    documentId: 'CMP016',
    status: 'Live',
    advertisments: [{ adType: 'Banner' }, { adType: 'Video' }],
  },
  {
    CampaignName: 'Thanksgiving',
    documentId: 'CMP017',
    status: 'Expired',
    advertisments: [{ adType: 'Banner' }],
  },
  {
    CampaignName: 'Christmas Countdown',
    documentId: 'CMP018',
    status: 'Draft',
    advertisments: [{ adType: 'Video' }],
  },
  {
    CampaignName: 'Boxing Day',
    documentId: 'CMP019',
    status: 'Live',
    advertisments: [{ adType: 'Banner' }, { adType: 'Banner' }],
  },
  {
    CampaignName: 'Year End Sale',
    documentId: 'CMP020',
    status: 'Expired',
    advertisments: [{ adType: 'Video' }],
  },
  {
    CampaignName: 'Flash Sale',
    documentId: 'CMP021',
    status: 'Draft',
    advertisments: [{ adType: 'Banner' }],
  },
  {
    CampaignName: 'Mega Discount',
    documentId: 'CMP022',
    status: 'Live',
    advertisments: [{ adType: 'Video' }],
  },
  {
    CampaignName: 'Anniversary Offer',
    documentId: 'CMP023',
    status: 'Expired',
    advertisments: [{ adType: 'Banner' }, { adType: 'Video' }],
  },
  {
    CampaignName: 'Weekend Bonanza',
    documentId: 'CMP024',
    status: 'Draft',
    advertisments: [{ adType: 'Banner' }],
  },
  {
    CampaignName: 'Clearance Event',
    documentId: 'CMP025',
    status: 'Live',
    advertisments: [{ adType: 'Video' }],
  },
  {
    CampaignName: 'VIP Exclusive',
    documentId: 'CMP026',
    status: 'Expired',
    advertisments: [{ adType: 'Banner' }],
  },
  {
    CampaignName: 'Loyalty Rewards',
    documentId: 'CMP027',
    status: 'Draft',
    advertisments: [{ adType: 'Banner' }, { adType: 'Video' }],
  },
  {
    CampaignName: 'Birthday Bash',
    documentId: 'CMP028',
    status: 'Live',
    advertisments: [{ adType: 'Video' }],
  },
  {
    CampaignName: 'Student Special',
    documentId: 'CMP029',
    status: 'Expired',
    advertisments: [{ adType: 'Banner' }],
  },
  {
    CampaignName: "Mother's Day",
    documentId: 'CMP030',
    status: 'Draft',
    advertisments: [{ adType: 'Banner' }, { adType: 'Video' }],
  },
  {
    CampaignName: "Father's Day",
    documentId: 'CMP031',
    status: 'Live',
    advertisments: [{ adType: 'Video' }],
  },
  {
    CampaignName: 'Travel Deals',
    documentId: 'CMP032',
    status: 'Expired',
    advertisments: [{ adType: 'Banner' }],
  },
  {
    CampaignName: 'Pet Lovers',
    documentId: 'CMP033',
    status: 'Draft',
    advertisments: [{ adType: 'Banner' }, { adType: 'Video' }],
  },
  {
    CampaignName: 'Tech Expo',
    documentId: 'CMP034',
    status: 'Live',
    advertisments: [{ adType: 'Video' }],
  },
  {
    CampaignName: 'Gadget Fest',
    documentId: 'CMP035',
    status: 'Expired',
    advertisments: [{ adType: 'Banner' }],
  },
  {
    CampaignName: 'Book Fair',
    documentId: 'CMP036',
    status: 'Draft',
    advertisments: [{ adType: 'Banner' }, { adType: 'Video' }],
  },
  {
    CampaignName: 'Music Mania',
    documentId: 'CMP037',
    status: 'Live',
    advertisments: [{ adType: 'Video' }],
  },
  {
    CampaignName: 'Art Attack',
    documentId: 'CMP038',
    status: 'Expired',
    advertisments: [{ adType: 'Banner' }],
  },
  {
    CampaignName: 'Fitness Frenzy',
    documentId: 'CMP039',
    status: 'Draft',
    advertisments: [{ adType: 'Banner' }, { adType: 'Video' }],
  },
  {
    CampaignName: 'Green Week',
    documentId: 'CMP040',
    status: 'Live',
    advertisments: [{ adType: 'Video' }],
  },
  {
    CampaignName: 'Backyard BBQ',
    documentId: 'CMP041',
    status: 'Expired',
    advertisments: [{ adType: 'Banner' }],
  },
  {
    CampaignName: 'Winter Wonderland',
    documentId: 'CMP042',
    status: 'Draft',
    advertisments: [{ adType: 'Video' }],
  },
  {
    CampaignName: 'Spring Fling',
    documentId: 'CMP043',
    status: 'Live',
    advertisments: [{ adType: 'Banner' }, { adType: 'Video' }],
  },
  {
    CampaignName: 'Fall Festival',
    documentId: 'CMP044',
    status: 'Expired',
    advertisments: [{ adType: 'Banner' }],
  },
  {
    CampaignName: 'Summer Bash',
    documentId: 'CMP045',
    status: 'Draft',
    advertisments: [{ adType: 'Video' }],
  },
  {
    CampaignName: 'Holiday Cheer',
    documentId: 'CMP046',
    status: 'Live',
    advertisments: [{ adType: 'Banner' }],
  },
  {
    CampaignName: "New Year's Eve",
    documentId: 'CMP047',
    status: 'Expired',
    advertisments: [{ adType: 'Banner' }, { adType: 'Video' }],
  },
  {
    CampaignName: "Valentine's Bash",
    documentId: 'CMP048',
    status: 'Draft',
    advertisments: [{ adType: 'Video' }],
  },
  {
    CampaignName: 'Easter Egg Hunt',
    documentId: 'CMP049',
    status: 'Live',
    advertisments: [{ adType: 'Banner' }],
  },
  {
    CampaignName: 'Spring Break',
    documentId: 'CMP050',
    status: 'Expired',
    advertisments: [{ adType: 'Banner' }, { adType: 'Video' }],
  },
];
